### ISSUE TITLE
Is there a way to download this app?

### ISSUE THREAD

**Issue by kyoyacchi** [lexwilliam/Risuto#2]
Or will you add this app to play store? Release date when? I can't wait to download this app.

**Comment by lexwilliam** [comment]
The app is almost done but I can't figure out how to publish it to the play store because my debit card issue. Maybe I will release the apk in this GitHub page soon.

**Comment by lexwilliam** [comment]
@kyoyacchi you can download it now in the release page

**Comment by kyoyacchi** [comment]
> @kyoyacchi you can download it now in the release page

Thanks. I'll install in no time. Good job.
