### ISSUE TITLE
Login button cropped

### ISSUE THREAD

**Issue by Art0343** [lexwilliam/Risuto#4]
![Screenshot_20220323-233128](https://user-images.githubusercontent.com/91286865/159766440-3515424b-ae87-4d79-8af0-f4de761ec62f.png)

The login button is cropped on my device.
When i press at the very bottom of the screen it takes me to the mal site and ask for Authorization.
After that it works well.
Device: Lenovo K8 Note ( Android 8 )

**Comment by lexwilliam** [comment]
is it only for the login screen ? is all the other screen not cropped ?

**Comment by lexwilliam** [comment]
oh wait i think i found the problem, the image push off the views in the bottom.

**Comment by lexwilliam** [comment]
it is fixed in version 0.8.1-alpha

**Comment by kyoyacchi** [comment]
> it is fixed in version 0.8.1-alpha

Are you sure about that?
![Screenshot_2022-04-01-01-25-13](https://user-images.githubusercontent.com/63583961/161159727-9bdd7489-f4fa-45f5-8a0e-c9d0a349e673.png)

I guess it's happening because LG's bottombar hide-show feature

**Comment by lexwilliam** [comment]
Oops my bad, maybe i make the button more in the center in the next patch.
