### ISSUE TITLE
Suggestions #2

### ISSUE THREAD

**Issue by Art0343** [lexwilliam/Risuto#6]
![Screenshot_20220327-184009](https://user-images.githubusercontent.com/91286865/160282985-72f324bf-71b5-4e08-8fec-70c3fa831247.png)
Instead of showing "Score" besides "watching/on hold".
It will be better to display the number of episodes you have watched like " watching 8/12" and move the score on top of the poster. Same with on-hold,dropped category.

Also add something like this in the watching section
![Screenshot_20220327-184759](https://user-images.githubusercontent.com/91286865/160283405-19876e59-5688-4cd2-acf2-7d1e61933da1.jpg)

Will be easier to add/deduct episodes quickly.

**Comment by lexwilliam** [comment]
That is a good idea!! Do you thing this works for grid views? Or I have to change it to row views so it can display more content ? Or both ?

**Comment by Art0343** [comment]
I think changing it to row view will be better.
You can add more information like "next episode in X days and X hours.
For reference: ( Otraku anilist client )
![Screenshot_20220327-220012](https://user-images.githubusercontent.com/91286865/160291238-937add78-90ac-4429-a894-8026a092c72d.png)

**Comment by lexwilliam** [comment]
I made the add episode function in the 0.8.2-alpha
