### ISSUE TITLE
Doesn't show some anime informations 

### ISSUE THREAD

**Issue by kyoyacchi** [lexwilliam/Risuto#7]
Like this.
![Screenshot_2022-04-01-01-42-17](https://user-images.githubusercontent.com/63583961/161161535-d362747b-f203-465b-8cbe-9221afa71415.png) (the quintessential quintuplets season 2)
and 
![Screenshot_2022-04-01-01-42-48](https://user-images.githubusercontent.com/63583961/161161633-77d774be-4792-480b-852a-f90bd169e88e.png) (the quintessential quintuplets season 2)
or 
this
![Screenshot_2022-04-01-01-42-26](https://user-images.githubusercontent.com/63583961/161161673-079bf95f-f989-428d-b545-49bb6d4bed02.png) (Kamisama no Memochou, i didn't watch this anime yet.)

I don't know if it's happening because of my list.

**Comment by lexwilliam** [comment]
What is the status for gotoubun no hanayome s2 originally ? When i open mine it works perfectly.

**Comment by lexwilliam** [comment]
Is it only for those two detail or all of the anime detail ? If you relaunch the app, is the issue gone ?

**Comment by kyoyacchi** [comment]
> Is it only for those two detail or all of the anime detail ? If you relaunch the app, is the issue gone ?

Sorry for late reply. No the issue is same even if you relaunch the app. the quintessential quintuplets bug fixed, i was forgot to add it to Completed from Plan to Watch thats why, it says "Error". The other one is is still same doesn't shows anything even if i relaunch the app. (English isn't my native language.)

**Comment by lexwilliam** [comment]
I found the problem for Kamisama no Memochou, it because for some reason there is no broadcast start time when i call from the api. So it has NullPointerException error. I fix it in 0.8.2-alpha. For the error status, is it fix now ? If it is fix now, i don't know if it is a myanimelist api bug or my app so can you describe the procedure how to recreate the error ? Thanks for the calling this issue tho, because there is so many anime in the api that some of the attribute can be null and result in this error.

**Comment by kyoyacchi** [comment]
> I found the problem for Kamisama no Memochou, it because for some reason there is no broadcast start time when i call from the api. So it has NullPointerException error. I fix it in 0.8.2-alpha. For the error status, is it fix now ? If it is fix now, i don't know if it is a myanimelist api bug or my app so can you describe the procedure how to recreate the error ? Thanks for the calling this issue tho, because there is so many anime in the api that some of the attribute can be null and result in this error.

- (Sorry for late reply, again.) I see...By the way, yep, it looks like it's fine now. Thanks for fixing it. Keep it up!
