### ISSUE TITLE
Suggestion: Adding profile page would be good in My List page

### ISSUE THREAD

**Issue by kyoyacchi** [lexwilliam/Risuto#8]
It really would be good, if it'd have profile like in official mal app , but with better interface.

For example, clicking the profile picture on "My List" next to nickname, will open the profile page.

This is MAL's official app's profile page... (Ugh ....)
![Screenshot_20220419-225857](https://user-images.githubusercontent.com/63583961/164086468-dde5b99e-f23f-444e-a575-d62e1ac07513.jpg)

And that's the AL-chan's (One of Anilist app) Unofficial app's profile page.
![Screenshot_20220419-230422](https://user-images.githubusercontent.com/63583961/164086707-8e0f4669-e453-40dd-984d-b454aa58bf19.jpg)

And that's the stats page of AnYme X 
![Ekran görüntüsü_20220419-230552](https://user-images.githubusercontent.com/63583961/164086885-c5f1cff5-1e63-4342-b950-f6b7ecd3daae.png)

I didn't see any *unofficial*  apps of MAL has profile page, so having in Risuto will be good, I think.

The design is up to you, but i do not know if MAL's API allows you to get those datas. Maybe Unofficial one (Jikan) does it...

**Comment by lexwilliam** [comment]
Yeah you're correct, the MAL's API didn't allow those datas. Jikan does it. Maybe i add it in the future

**Comment by lexwilliam** [comment]
Sorry its been almost four months without update lol, i have been proscrastinating and busy with university stuff. I build the profile page in version 0.9.5-alpha. Maybe i have more motivation now because i only need to implement one more feature for the 1.0.0 version. Thanks for the suggestion as always

**Comment by kyoyacchi** [comment]
> Sorry its been almost four months without update lol, i have been proscrastinating and busy with university stuff. I build the profile page in version 0.9.5-alpha. Maybe i have more motivation now because i only need to implement one more feature for the 1.0.0 version. Thanks for the suggestion as always

No problem. Thank you for adding it. It looks very good, gochisousama deshita.
